#include <stdio.h>

#include "compiler.h"
#include "rbtree.h"
#include "list.h"
#include "co.h"
#include "co_inner.h"

#define DEFINE(sym, val) \
    printf("#define " #sym " %d\n", val)

#define OFFSET(sym, type, mem) \
    DEFINE(sym, offsetof(type, mem))

int main(void)
{
    printf("/*\n"
           " * DO NOT MODIFY\n"
           " *\n"
           " * This file was generated by Makefile\n"
           " */\n"
    );
    OFFSET(CO_rsp, co_t, rsp);
    OFFSET(CO_stack, co_t, stack);
    OFFSET(CO_stack_size, co_t, stack_size);
    OFFSET(CO_id, co_t, id);
}